### ISSUE TITLE
Add a second gateway (copy code but not hyperbee contents)

### ISSUE THREAD

**Issue by katelynsills** [starlinglab/authenticated-attributes#18]
For demo purposes, we want to be able to show that a user is able to view data from multiple sources in the UWAZI UI, and if data is added to a source, it gets automatically populated in the UI. In order to do this, we need to run a second Hyperbee gateway, allow for some sort of script or endpoint to add data to the Hyperbee instance, and then ensure that the UI is connected to this gateway as well as the primary Starling one. Even though we need a way to add data to the Hyperbee instance, this gateway is still just read-only in terms of the API.

The data in the second Hyperbee gateway won't include what is in the primary Starling gateway. This is meant to emulate data from a second source, so the data does not necessarily need to be accurate or helpful. For instance, the data could simply be adding a more descriptive title/name. 

See #3 for the issue to add the primary gateway.

**Comment by makew0rld** [comment]
My understanding of this issue is that it would be an action for deployment of the demo, not something that can be committed to the repo right now. The existing gateway code would be running twice (on two different ports or something), and with a few commands, a new hypercore would be made with a some dummy data in it.

**Comment by katelynsills** [comment]
Closing this as finished! Thanks @makew0rld !
